apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: my-flask-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_APP
          valueFrom:
            secretKeyRef:
              name: flask-secrets
              key: FLASK_APP
        - name: FLASK_ENV
          valueFrom:
            secretKeyRef:
              name: flask-secrets
              key: FLASK_ENV
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: flask-secrets
              key: SECRET_KEY
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: flask-secrets
              key: USERNAME
        - name: PASSWORD_HASH
          valueFrom:
            secretKeyRef:
              name: flask-secrets
              key: PASSWORD_HASH